### PR TITLE
fixed warnings and minor changes

### PR DESCRIPTION
**Pull request by berghetti**
* fix warnings
* fix memory leaks
* added code style witch file .clang-format
* added file .gitignore
* minor changes from code

### CODE REVIEW

**Comment by eribertomota** [comment]
Hi @berghetti,

Thanks a lot for your help and sorry for my long delay.

I would like to ask for some changes, so please:
* Don't break the lines in "USA" word. This is the official license text from FSF, checked by some systems. Also, all current and modern systems aren't limited to 80 columns. Thus, in this specific point, is not needed a break.
* Don't set a static CFLAGS. When using autotools, options for CFLAGS can be set via command line. Making a static CFLAGS will force some unneeded options for the final users and will cause some issues on some systems, like Debian because it won't be able to set hardening building flags imposed by its policy.
* Finally, please, in next time, try to make a separate PR for each issue/subject.

Thanks again for your work.

**Comment by eribertomota** [comment]
I edited the my comment above. s/separate commit for/separate PR for/

**Comment by berghetti** [comment]
hi @eribertomota,
added two new commits with the fixes.

the first question was generated by the automatic code indentation tool clang-format.

the second was the only way I managed to include the CFLGAS,
how could I do to include the CGLAFS with this autotool?

Thanks.

**Comment by eribertomota** [comment]
To make tests, you can use the following command:

`./configure CFLAGS="-pedantic -Wall -Wextra -Wformat"`

Thanks!

**Comment by eribertomota** [comment]
Please, check other options running `./configure --help`

**Comment by eribertomota** [comment]
Thanks a lot for your work. I will add your name to Copyright lines in headers.

**Pull request merged**
